# Generated by Django 5.2.10 on 2026-01-21 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 21, 17, 6, 40, 600343)),
        ),
    ]
