# Generated by Django 5.2.6 on 2026-01-04 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_accounts',
            name='username',
            field=models.CharField(default='tempuser', max_length=50, unique=True),
        ),
    ]
